// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN4ajyTzCuWXjdUmycoZzSBSMDZnaWOxc',
    appId: '1:949142340891:web:1484b5593e565fa4cebfbe',
    messagingSenderId: '949142340891',
    projectId: 'carpoolingprojectfyp',
    authDomain: 'carpoolingprojectfyp.firebaseapp.com',
    storageBucket: 'carpoolingprojectfyp.appspot.com',
    measurementId: 'G-294C4L65TP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ0u7SjmKFasIaaJaoXJVymvBFCWYlApk',
    appId: '1:949142340891:android:8aaeb8fd3653707ecebfbe',
    messagingSenderId: '949142340891',
    projectId: 'carpoolingprojectfyp',
    storageBucket: 'carpoolingprojectfyp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDprRIU8bInZYT3qdBw6F4VqrFghsW-q70',
    appId: '1:949142340891:ios:59211eb3c3ef5f70cebfbe',
    messagingSenderId: '949142340891',
    projectId: 'carpoolingprojectfyp',
    storageBucket: 'carpoolingprojectfyp.appspot.com',
    iosBundleId: 'com.example.flutterApplicationTesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDprRIU8bInZYT3qdBw6F4VqrFghsW-q70',
    appId: '1:949142340891:ios:59211eb3c3ef5f70cebfbe',
    messagingSenderId: '949142340891',
    projectId: 'carpoolingprojectfyp',
    storageBucket: 'carpoolingprojectfyp.appspot.com',
    iosBundleId: 'com.example.flutterApplicationTesting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN4ajyTzCuWXjdUmycoZzSBSMDZnaWOxc',
    appId: '1:949142340891:web:652e786adebbbd96cebfbe',
    messagingSenderId: '949142340891',
    projectId: 'carpoolingprojectfyp',
    authDomain: 'carpoolingprojectfyp.firebaseapp.com',
    storageBucket: 'carpoolingprojectfyp.appspot.com',
    measurementId: 'G-QDPEEY81XW',
  );
}
